name: user_srv
port: 0
ip: 10.3.189.2

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: 2201a

consul:
  host: 127.0.0.1
  port: 8500
  tags:
    - user_srv
    - goods
    - wujuan
